---

name: Publish as Node Package

# publish on every tags push
on:
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" | tee .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" | tee .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
