# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish as Node Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
          token: ${{secrets.NPM_TOKEN}}
      - run: npm ci
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
